import { join } from "node:path";

const node = process.execPath;
const powershell = process.env.SSE_POWERSHELL_EXE ??
  join(process.env.SystemRoot ?? process.env.WINDIR ?? "C:\\Windows", "System32", "WindowsPowerShell", "v1.0", "powershell.exe");
const psFile = (name, file) => ({
  name,
  command: powershell,
  args: ["-NoLogo", "-NoProfile", "-NonInteractive", "-ExecutionPolicy", "Bypass", "-File", file],
});
const nodeFile = (name, file, ...args) => ({ name, command: node, args: [file, ...args] });
const withApi = (name, file, ...args) => nodeFile(name, "test/with-api.mjs", node, file, ...args);
export const WORKER_CONTROLLER_CONFLICT_KEY = "windows-session-worker-controller";
const workerControllerSteps = new Set([
  "archive-cases", "archive-cases-synthetic", "archive-local-parity",
  "backup-cases-contract", "backup-local-parity", "bulk-action-worker-contract",
  "case-file", "checker-open-contract", "direct-worker-collection-guard",
  "desktop-marker-contract",
  "direct-worker-experimental-guard", "direct-worker-file-guard", "direct-worker-guard",
  "direct-worker-identity-guard", "direct-worker-resource-guard", "file-operations-worker",
  "launch-orchestration", "mcp-selftest", "product-gate", "verify-collect",
  "verify-local-parity", "worker-inherited-pipe", "worker-input-file-contract",
  "worker-output-file-contract", "worker-timeout", "working-copy-local-parity",
]);

export const serialBuildSteps = Object.freeze([
  nodeFile("dist-prune", "scripts/prune-dist.mjs"),
  psFile("native-build", "powershell/build-native.ps1"),
  nodeFile("typescript-build", "node_modules/typescript/bin/tsc"),
  nodeFile("npm-package-build", "scripts/build-npm-packages.mjs"),
  nodeFile("agent-plugin-build", "scripts/build-agent-plugin.mjs", "--check"),
]);

export const parallelSteps = Object.freeze([
  nodeFile("suite-runner-contract", "test/suite-runner-contract.mjs"),
  nodeFile("public-skills", "test/public-skills.mjs"),
  nodeFile("repository-privacy", "test/repository-privacy-contract.mjs"),
  nodeFile("repository-links", "test/repository-links-contract.mjs"),
  nodeFile("readme-contract", "test/readme-contract.mjs"),
  nodeFile("github-workflow", "test/github-workflow-contract.mjs"),
  nodeFile("javascript-syntax", "test/javascript-syntax-contract.mjs"),
  psFile("powershell-syntax", "test/powershell-syntax-contract.ps1"),
  psFile("tracked-date-rollback", "test/tracked-date-rollback-contract.ps1"),
  psFile("value-info-window", "test/value-info-window-contract.ps1"),
  psFile("write-window-binding", "test/write-window-binding-contract.ps1"),
  psFile("case-binding", "test/case-binding-contract.ps1"),
  psFile("recovery-answer-policy", "test/recovery-answer-policy-contract.ps1"),
  psFile("update-prompt", "test/update-prompt-contract.ps1"),
  psFile("heading-cache", "test/heading-cache-contract.ps1"),
  psFile("desktop-stop-policy", "test/desktop-stop-policy-contract.ps1"),
  psFile("process-command-line", "test/process-command-line-contract.ps1"),
  psFile("process-exit-wait", "test/process-exit-wait-contract.ps1"),
  psFile("describe-point-basic", "test/describe-point-basic-contract.ps1"),
  psFile("dialog-fingerprint", "test/dialog-fingerprint-contract.ps1"),
  psFile("content-bounds", "test/content-bounds-contract.ps1"),
  psFile("aside-corners", "test/aside-corners-contract.ps1"),
  psFile("uia-proxy-state", "test/uia-proxy-state-contract.ps1"),
  psFile("tool-window-close", "test/tool-window-close-contract.ps1"),
  psFile("tool-window-read", "test/tool-window-read-contract.ps1"),
  psFile("receipt-manager-action", "test/receipt-manager-action-contract.ps1"),
  nodeFile("bulk-action-executor", "test/bulk-action-executor.mjs"),
  nodeFile("bulk-action-worker-contract", "test/bulk-action-worker-contract.mjs"),
  psFile("desktop-enumeration", "test/desktop-enumeration-contract.ps1"),
  psFile("window-restore-contract", "test/window-restore-contract.ps1"),
  nodeFile("foreground-lease-contract", "test/foreground-lease-contract.mjs"),
  nodeFile("desktop-marker-contract", "test/desktop-marker-contract.mjs"),
  psFile("desktop-marker-write-contract", "test/desktop-marker-write-contract.ps1"),
  nodeFile("focusless-commit-contract", "test/focusless-commit-contract.mjs"),
  nodeFile("file-dialog-folder-contract", "test/file-dialog-folder-contract.mjs"),
  nodeFile("native-build-cache", "test/native-build-cache.mjs"),
  nodeFile("direct-worker-guard", "test/direct-worker-guard.mjs"),
  nodeFile("direct-worker-experimental-guard", "test/direct-worker-experimental-guard.mjs"),
  psFile("experimental-dialog-policy", "test/experimental-dialog-policy-contract.ps1"),
  nodeFile("startup-dialog-policy", "test/startup-dialog-policy-contract.mjs"),
  nodeFile("direct-worker-resource-guard", "test/direct-worker-resource-guard.mjs"),
  nodeFile("direct-worker-file-guard", "test/direct-worker-file-guard.mjs"),
  nodeFile("worker-input-file-contract", "test/worker-input-file-contract.mjs"),
  nodeFile("direct-worker-collection-guard", "test/direct-worker-collection-guard.mjs"),
  nodeFile("worker-progress-contract", "test/worker-progress-contract.mjs"),
  nodeFile("table-add-rollback-contract", "test/table-add-rollback-contract.mjs"),
  nodeFile("table-delete-rebinding", "test/table-delete-rebinding-contract.mjs"),
  nodeFile("table-window-scope", "test/table-window-scope-contract.mjs"),
  nodeFile("dirty-state-binding", "test/dirty-state-binding-contract.mjs"),
  withApi("verify-collect", "test/verify-collect.mjs"),
  nodeFile("verify-local-parity", "test/verify-local-parity.mjs"),
  nodeFile("working-copy-local-parity", "test/working-copy-local-parity.mjs"),
  withApi("file-operations-worker", "test/file-operations-worker.mjs"),
  nodeFile("product-profiles", "test/product-profiles.mjs"),
  nodeFile("page-objects-parity", "test/page-objects-parity.mjs"),
  nodeFile("product-profile-status", "test/product-profile-status-contract.mjs"),
  nodeFile("profile-operation-policy", "test/profile-operation-policy.mjs"),
  nodeFile("receipt-interaction-policy", "test/receipt-interaction-policy.mjs"),
  nodeFile("belegmanager-config-isolation", "test/belegmanager-config-isolation.mjs"),
  nodeFile("api-mega-contract", "test/performance/api-mega-contract.mjs"),
  psFile("akad-parser", "test/akad-parser-contract.ps1"),
  psFile("table-combobox-contract", "test/table-combobox-contract.ps1"),
  nodeFile("table-combobox-guard", "test/table-combobox-guard.mjs"),
  nodeFile("case-file", "test/case-file-contract.mjs"),
  nodeFile("pdf-render-helper", "test/pdf-render-helper.mjs"),
  nodeFile("atomic-files", "test/atomic-files.mjs"),
  nodeFile("jsonl-logger", "test/jsonl-logger.mjs"),
  nodeFile("dist-artifacts", "test/dist-artifacts-contract.mjs"),
  nodeFile("release-metadata", "test/release-metadata-contract.mjs"),
  nodeFile("agent-plugin-contract", "test/agent-plugin-contract.mjs"),
  nodeFile("npm-package", "test/npm-package-contract.mjs"),
  nodeFile("workspace-containment", "test/workspace-containment.mjs"),
  nodeFile("workspace-file-cancellation", "test/workspace-file-cancellation.mjs"),
  nodeFile("resource-references", "test/resource-references.mjs"),
  nodeFile("live-script-resource-contract", "test/live-script-resource-contract.mjs"),
  nodeFile("backup-cases-contract", "test/backup-cases-contract.mjs"),
  nodeFile("backup-local-parity", "test/backup-local-parity.mjs"),
  nodeFile("archive-cases-synthetic", "test/archive-cases-synthetic.mjs"),
  nodeFile("archive-local-parity", "test/archive-local-parity.mjs"),
  nodeFile("sse-process-guard", "test/sse-process-guard.mjs"),
  psFile("desktop-launcher", "test/desktop-launcher-contract.ps1"),
  nodeFile("api-contract", "test/api-contract.mjs"),
  nodeFile("api-static-documents", "test/api-static-document-cache.mjs"),
  nodeFile("api-client-body-abort", "test/api-client-body-abort.mjs"),
  nodeFile("api-client-transport-timeout", "test/api-client-transport-timeout.mjs"),
  nodeFile("api-local-http-transport", "test/api-local-http-transport.mjs"),
  nodeFile("api-single-flight", "test/api-single-flight.mjs"),
  nodeFile("checker-open-contract", "test/checker-open-contract.mjs"),
  nodeFile("api-discovery-contract", "test/api-discovery-contract.mjs"),
  nodeFile("api-openapi-contract", "test/api-openapi-contract.mjs"),
  nodeFile("api-cli-contract", "test/api-cli-contract.mjs"),
  nodeFile("api-config-contract", "test/api-config-contract.mjs"),
  nodeFile("api-all-operations", "test/api-all-operations.mjs"),
  nodeFile("launch-orchestration", "test/launch-orchestration.mjs"),
  nodeFile("case-create-contract", "test/case-create-contract.mjs"),
  nodeFile("operation-schema-catalog", "test/operation-schema-catalog.mjs"),
  nodeFile("operation-coverage-merge", "test/operation-coverage-merge-contract.mjs"),
  nodeFile("verification-doc-coverage", "test/verification-doc-coverage-contract.mjs"),
  nodeFile("operation-result-shape-merge", "test/operation-result-shape-merge-contract.mjs"),
  nodeFile("operation-trace", "test/operation-trace-contract.mjs"),
  nodeFile("live-profile-read-coverage", "test/live-profile-read-coverage-contract.mjs"),
  nodeFile("operation-live-evidence", "test/operation-live-evidence-contract.mjs"),
  nodeFile("live-core-read-contract", "test/live-core-read-contract.mjs"),
  nodeFile("result-contract", "test/result-contract.mjs"),
  nodeFile("result-field-worker-guard", "test/result-field-worker-guard.mjs"),
  nodeFile("source-architecture", "test/source-architecture-contract.mjs"),
  nodeFile("no-year-conditionals", "test/no-year-conditionals-contract.mjs"),
  nodeFile("mcp-module-boundaries", "test/mcp-module-boundaries.mjs"),
  nodeFile("mcp-main-contract", "test/mcp-main-contract.mjs"),
  nodeFile("mcp-preflight", "test/mcp-preflight.mjs"),
  nodeFile("mcp-registry-contract", "test/mcp-registry-contract.mjs"),
  nodeFile("mcp-response-contract", "test/mcp-response-contract.mjs"),
  nodeFile("capabilities-contract", "test/capabilities-contract.mjs"),
  nodeFile("ustva-contract", "test/ustva-contract.mjs"),
  nodeFile("api-tax-journeys", "--test", "test/api-tax-journeys.mjs"),
  nodeFile("api-main-smoke", "test/api-main-smoke.mjs"),
  nodeFile("abort-contract", "test/abort-contract.mjs"),
  nodeFile("wrapper-boundary", "test/wrapper-boundary.mjs"),
  nodeFile("mcp-wrapper-catalog", "test/mcp-wrapper-all-tools.mjs"),
  nodeFile("mcp-api-all-operations", "test/mcp-api-all-operations.mjs"),
  nodeFile("mcp-cancellation", "test/mcp-cancellation.mjs"),
  nodeFile("worker-timeout", "test/worker-timeout.mjs"),
  nodeFile("worker-inherited-pipe", "test/worker-inherited-pipe.mjs"),
  nodeFile("worker-prewarm", "test/worker-prewarm.mjs"),
  nodeFile("worker-output-file-contract", "test/worker-output-file-contract.mjs"),
  nodeFile("direct-worker-identity-guard", "test/direct-worker-identity-guard.mjs"),
  nodeFile("direct-worker-native-guard", "test/direct-worker-native-guard.mjs"),
  nodeFile("scenario-parity", "test/scenario-parity.mjs"),
  nodeFile("scenario-control-flow", "test/scenario-control-flow.mjs"),
  withApi("mcp-selftest", "dist/index.js", "--selftest"),
  psFile("table-region", "test/table-region-contract.ps1"),
  psFile("table-values", "test/table-values-contract.ps1"),
  psFile("instance-identity", "test/instance-identity-contract.ps1"),
  psFile("window-scope", "test/window-scope-contract.ps1"),
  psFile("structure-binding", "test/structure-binding-contract.ps1"),
  psFile("snapshot-runtime-id", "test/snapshot-runtime-id-contract.ps1"),
  psFile("checker-zero-results", "test/checker-zero-results-contract.ps1"),
  psFile("build-drift", "test/build-drift-contract.ps1"),
  withApi("product-gate", "test/product-gate.mjs"),
  withApi("archive-cases", "test/archive-cases.mjs"),
].map((step) => workerControllerSteps.has(step.name)
  ? { ...step, conflictKey: WORKER_CONTROLLER_CONFLICT_KEY }
  : step));

export const exclusiveSteps = Object.freeze([
  { ...nodeFile("worker-controller-lock", "test/worker-controller-lock-contract.mjs"), timeoutMs: 420_000 },
  nodeFile("mcp-api-supervisor", "test/mcp-api-supervisor.mjs"),
  nodeFile("agent-plugin-runtime", "test/agent-plugin-runtime.mjs"),
  withApi("no-console-window", "test/no-console-window.mjs"),
]);

/**
 * Laufen zuletzt: beide Bilanzen werten das Laufzeitprotokoll aller vorherigen
 * Schritte aus und duerfen deshalb keinen davon parallel sehen.
 */
export const finalSteps = Object.freeze([
  nodeFile("operation-coverage", "test/operation-coverage-contract.mjs"),
  nodeFile("operation-result-shape", "test/operation-result-shape-contract.mjs"),
]);

const FAST_STEP_NAMES = new Set([
  "suite-runner-contract",
  "public-skills",
  "repository-privacy",
  "repository-links",
  "readme-contract",
  "github-workflow",
  "javascript-syntax",
  "powershell-syntax",
  "receipt-manager-action",
  "bulk-action-executor",
  "bulk-action-worker-contract",
  "tracked-date-rollback",
  "case-binding",
  "recovery-answer-policy",
  "update-prompt",
  "heading-cache",
  "desktop-stop-policy",
  "process-command-line",
  "process-exit-wait",
  "describe-point-basic",
  "desktop-enumeration",
  "window-restore-contract",
  "window-scope",
  "structure-binding",
  "snapshot-runtime-id",
  "checker-zero-results",
  "build-drift",
  "foreground-lease-contract",
  "desktop-marker-contract",
  "desktop-marker-write-contract",
  "focusless-commit-contract",
  "file-dialog-folder-contract",
  "atomic-files",
  "case-file",
  "jsonl-logger",
  "dist-artifacts",
  "release-metadata",
  "agent-plugin-contract",
  "workspace-containment",
  "workspace-file-cancellation",
  "resource-references",
  "live-script-resource-contract",
  "sse-process-guard",
  "api-contract",
  "api-static-documents",
  "api-client-body-abort",
  "api-client-transport-timeout",
  "api-local-http-transport",
  "api-single-flight",
  "checker-open-contract",
  "api-discovery-contract",
  "api-openapi-contract",
  "api-cli-contract",
  "api-config-contract",
  "product-profile-status",
  "profile-operation-policy",
  "receipt-interaction-policy",
  "belegmanager-config-isolation",
  "api-mega-contract",
  "table-combobox-contract",
  "direct-worker-experimental-guard",
  "experimental-dialog-policy",
  "startup-dialog-policy",
  "api-all-operations",
  "launch-orchestration",
  "case-create-contract",
  "operation-schema-catalog",
  "operation-coverage-merge",
  "verification-doc-coverage",
  "operation-result-shape-merge",
  "operation-trace",
  "live-profile-read-coverage",
  "operation-live-evidence",
  "live-core-read-contract",
  "result-contract",
  "result-field-worker-guard",
  "source-architecture",
  "no-year-conditionals",
  "mcp-module-boundaries",
  "mcp-main-contract",
  "mcp-preflight",
  "mcp-registry-contract",
  "mcp-response-contract",
  "capabilities-contract",
  "ustva-contract",
  "api-tax-journeys",
  "api-main-smoke",
  "abort-contract",
  "wrapper-boundary",
  "mcp-wrapper-catalog",
  "mcp-api-all-operations",
  "worker-timeout",
  "worker-progress-contract",
  "table-add-rollback-contract",
  "table-delete-rebinding",
  "table-window-scope",
  "dirty-state-binding",
  "table-values",
  "scenario-parity",
  "scenario-control-flow",
]);

export const fastBuildSteps = Object.freeze(
  serialBuildSteps.filter((step) => step.name === "dist-prune" || step.name === "typescript-build"),
);
export const fastSteps = Object.freeze(
  parallelSteps.filter((step) => FAST_STEP_NAMES.has(step.name)),
);
