export const SSE_EXPECTED_API_CONFIGURATION_FINGERPRINT =
  "SSE_INTERNAL_EXPECTED_API_CONFIGURATION_FINGERPRINT";
export const SSE_EXPECTED_API_BASE_URL = "SSE_INTERNAL_EXPECTED_API_BASE_URL";
export const SSE_API_INSTANCE_HEADER = "x-sse-api-instance-id";
